package main

// Command gen-places generates db/migrations/00006_seed_places.sql from
// tools/uk_places.tsv. Run from the repository root: go run ./tools/gen-places
//
// Place IDs are frozen in the TSV; this command validates and renders, it never mints.
// Use tools/refresh-places to add rows from a newer GeoNames dump.

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
)

const (
	inputPath  = "tools/uk_places.tsv"
	outputPath = "db/migrations/00006_seed_places.sql"
)

var placeIDPattern = regexp.MustCompile(`^plc_[a-z0-9]{26}$`)

type place struct {
	id          string
	geonamesID  int
	name        string
	latitude    string
	longitude   string
	population  int
	featureCode string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-places:", err)
		os.Exit(1)
	}
}

func run() error {
	places, err := readPlaces(inputPath)
	if err != nil {
		return err
	}
	if len(places) == 0 {
		return fmt.Errorf("no places parsed from %s", inputPath)
	}

	seenID := make(map[string]string, len(places))
	seenGeonamesID := make(map[int]string, len(places))

	for _, p := range places {
		if !placeIDPattern.MatchString(p.id) {
			return fmt.Errorf("id %q (%s) does not match %s", p.id, p.name, placeIDPattern)
		}
		if prev, dup := seenID[p.id]; dup {
			return fmt.Errorf("duplicate id %s shared by %q and %q", p.id, prev, p.name)
		}
		seenID[p.id] = p.name

		if prev, dup := seenGeonamesID[p.geonamesID]; dup {
			return fmt.Errorf("duplicate geonames_id %d shared by %q and %q", p.geonamesID, prev, p.name)
		}
		seenGeonamesID[p.geonamesID] = p.name
	}

	if err := os.WriteFile(outputPath, []byte(renderSQL(places)), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d places)\n", outputPath, len(places))
	return nil
}

func readPlaces(path string) ([]place, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()

	var places []place
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	first := true
	for sc.Scan() {
		line := sc.Text()
		if first {
			first = false
			continue
		}
		if strings.TrimSpace(line) == "" {
			continue
		}

		fields := strings.Split(line, "\t")
		if len(fields) != 7 {
			return nil, fmt.Errorf("expected 7 columns, got %d: %q", len(fields), line)
		}
		geonamesID, err := strconv.Atoi(fields[1])
		if err != nil {
			return nil, fmt.Errorf("geonames_id %q is not a number: %w", fields[1], err)
		}
		population, err := strconv.Atoi(fields[5])
		if err != nil {
			return nil, fmt.Errorf("population %q is not a number: %w", fields[5], err)
		}

		places = append(places, place{
			id: fields[0], geonamesID: geonamesID, name: fields[2],
			latitude: fields[3], longitude: fields[4],
			population: population, featureCode: fields[6],
		})
	}
	return places, sc.Err()
}

func renderSQL(places []place) string {
	var b strings.Builder
	b.WriteString("-- Code generated by tools/gen-places; DO NOT EDIT.\n")
	b.WriteString("-- Source of truth: tools/uk_places.tsv (regenerate via `go run ./tools/gen-places`).\n")
	b.WriteString("-- GeoNames (https://www.geonames.org/), CC BY 4.0.\n\n")
	b.WriteString("-- +goose Up\n")
	b.WriteString("INSERT INTO places (id, geonames_id, name, latitude, longitude, population, feature_code) VALUES\n")

	for i, p := range places {
		sep := ","
		if i == len(places)-1 {
			sep = ""
		}
		fmt.Fprintf(&b, "  ('%s', %d, '%s', %s, %s, %d, '%s')%s\n",
			p.id, p.geonamesID, sqlQuote(p.name), p.latitude, p.longitude, p.population, p.featureCode, sep)
	}

	b.WriteString("ON CONFLICT (id) DO NOTHING;\n")
	b.WriteString("\n-- +goose Down\n")
	b.WriteString("-- No-op: 00005 drops the table.\n")
	b.WriteString("SELECT 1;\n")
	return b.String()
}

func sqlQuote(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}
