package main

// Command gen-seed generates db/migrations/00002_seed_birds.sql from
// tools/uk_birds.tsv. Run from the repository root: go run ./tools/gen-seed
//
// Bird IDs are frozen in the TSV to preserve referential integrity with
// existing sightings; once 00002 has shipped, add or change birds via a new
// migration instead of regenerating this file.

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strings"
)

const (
	inputPath  = "tools/uk_birds.tsv"
	outputPath = "db/migrations/00002_seed_birds.sql"
)

var birdIDPattern = regexp.MustCompile(`^brd_[a-z0-9]{26}$`)

type bird struct {
	id             string
	commonName     string
	scientificName string
	ebirdCode      string
	taxonomicOrder int
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-seed:", err)
		os.Exit(1)
	}
}

func run() error {
	birds, err := readBirds(inputPath)
	if err != nil {
		return err
	}
	if len(birds) == 0 {
		return fmt.Errorf("no birds parsed from %s", inputPath)
	}

	seenID := make(map[string]string, len(birds))
	seenCode := make(map[string]string, len(birds))

	for _, b := range birds {
		if !birdIDPattern.MatchString(b.id) {
			return fmt.Errorf("id %q (%s) does not match %s", b.id, b.scientificName, birdIDPattern)
		}
		if prev, dup := seenID[b.id]; dup {
			return fmt.Errorf("duplicate id %s shared by %q and %q", b.id, prev, b.scientificName)
		}
		seenID[b.id] = b.scientificName

		if b.ebirdCode != "" {
			if prev, dup := seenCode[b.ebirdCode]; dup {
				return fmt.Errorf("duplicate ebird_code %s shared by %q and %q", b.ebirdCode, prev, b.scientificName)
			}
			seenCode[b.ebirdCode] = b.scientificName
		}
	}

	if err := os.WriteFile(outputPath, []byte(renderSQL(birds)), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d species)\n", outputPath, len(birds))
	return nil
}

// readBirds parses the TSV (id, common_name, scientific_name, [ebird_code]), deriving taxonomic_order from the row's 1-based position.
func readBirds(path string) ([]bird, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()

	var birds []bird
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)

	first := true
	for sc.Scan() {
		line := sc.Text()
		if first {
			first = false
			continue
		}
		if strings.TrimSpace(line) == "" {
			continue
		}
		cols := strings.Split(line, "\t")
		if len(cols) < 3 {
			return nil, fmt.Errorf("malformed row: %q", line)
		}

		b := bird{
			id:             strings.TrimSpace(cols[0]),
			commonName:     strings.TrimSpace(cols[1]),
			scientificName: strings.TrimSpace(cols[2]),
			taxonomicOrder: len(birds) + 1,
		}
		if len(cols) >= 4 {
			b.ebirdCode = strings.TrimSpace(cols[3])
		}

		if b.commonName == "" || b.scientificName == "" {
			return nil, fmt.Errorf("missing name in row: %q", line)
		}
		birds = append(birds, b)
	}
	return birds, sc.Err()
}

func renderSQL(birds []bird) string {
	var b strings.Builder
	b.WriteString("-- Code generated by tools/gen-seed; DO NOT EDIT.\n")
	b.WriteString("-- Source of truth: tools/uk_birds.tsv (regenerate via `go run ./tools/gen-seed`).\n")
	b.WriteString("-- UK bird reference list (BOU British List), list order preserved as taxonomic_order.\n\n")
	b.WriteString("-- +goose Up\n")
	b.WriteString("INSERT INTO birds (id, common_name, scientific_name, ebird_code, taxonomic_order) VALUES\n")

	for i, bd := range birds {
		sep := ","
		if i == len(birds)-1 {
			sep = ""
		}
		fmt.Fprintf(&b, "  ('%s', '%s', '%s', %s, %d)%s\n",
			bd.id,
			sqlQuote(bd.commonName),
			sqlQuote(bd.scientificName),
			sqlNullableText(bd.ebirdCode),
			bd.taxonomicOrder,
			sep,
		)
	}

	// DO NOTHING makes re-applying the seed a safe no-op instead of crashing on primary key conflicts.
	b.WriteString("ON CONFLICT (id) DO NOTHING;\n")

	b.WriteString("\n-- +goose Down\n")
	b.WriteString("-- No-op: migration 00001 drops the birds table, which removes these rows.\n")
	b.WriteString("-- A DELETE here would violate the sightings.bird_id foreign key when sightings exist.\n")
	b.WriteString("SELECT 1;\n")
	return b.String()
}

func sqlQuote(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}

func sqlNullableText(s string) string {
	if s == "" {
		return "NULL"
	}
	return "'" + sqlQuote(s) + "'"
}
